const priorities=['Housing affordability','Homeownership','Crime / public safety','Youth programs','Jobs and wages','Grocery / food access','Vacant properties','Landlord / code enforcement','Neighborhood businesses','Transportation','Schools','Roads / infrastructure'];
const responsibilities=['City government','County government','School district','Landlords / property owners','Businesses / developers','Police / public safety agencies','Neighborhood organizations','Residents themselves','State / federal government'];
const actions=['Vote in local elections','Attend a neighborhood meeting','Attend a City Council meeting','Volunteer','Join a neighborhood association','Support neighborhood businesses','Participate in cleanups / improvement projects','Work toward homeownership','Mentor youth','Serve on a board or committee'];
let step=0;const steps=[...document.querySelectorAll('.step')];
const form=document.getElementById('surveyForm'),next=document.getElementById('nextBtn'),back=document.getElementById('backBtn'),submit=document.getElementById('submitBtn'),nav=document.getElementById('navButtons'),bar=document.getElementById('progressBar');
function renderOptions(id,name,items,max){document.getElementById(id).innerHTML=items.map(x=>`<label class="option"><input type="checkbox" name="${name}" value="${x}">${x}</label>`).join('');if(max){document.querySelectorAll(`input[name="${name}"]`).forEach(el=>el.addEventListener('change',()=>{const chosen=[...document.querySelectorAll(`input[name="${name}"]:checked`)];document.querySelectorAll(`input[name="${name}"]:not(:checked)`).forEach(i=>i.disabled=chosen.length>=max)}));}}
renderOptions('priorityOptions','priorities',priorities,3);renderOptions('responsibilityOptions','responsibilities',responsibilities);renderOptions('actionOptions','actions',actions);
function show(){steps.forEach((s,i)=>s.classList.toggle('hidden',i!==step));bar.style.width=`${((step+1)/steps.length)*100}%`;back.classList.toggle('hidden',step===0||step===6);next.classList.toggle('hidden',step>=5);submit.classList.toggle('hidden',step!==5);nav.classList.toggle('hidden',step===6);}
function validCurrent(){const current=steps[step];if(step===0&&!current.querySelector('input[name="role"]:checked'))return false;if(step===1&&!current.querySelector('select[name="neighborhood"]').value)return false;if(step===2&&current.querySelectorAll('input[name="priorities"]:checked').length===0)return false;return true;}
next.onclick=()=>{if(!validCurrent()){alert('Please complete this step before continuing.');return;}step++;show()};back.onclick=()=>{step--;show()};
document.getElementById('contactOptIn').addEventListener('change',e=>document.getElementById('emailWrap').classList.toggle('hidden',!e.target.checked));
const qp=new URLSearchParams(location.search);document.getElementById('sourceField').value=qp.get('source')||'direct';document.getElementById('campaignField').value=qp.get('campaign')||'organic';document.getElementById('responseId').value=(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));
if(window.ONE_SCHENECTADY_CONFIG.DATA_ENDPOINT){form.action=window.ONE_SCHENECTADY_CONFIG.DATA_ENDPOINT;}else{submit.disabled=true;submit.textContent='Data endpoint not connected';}
form.addEventListener('submit',()=>{setTimeout(()=>{step=6;show()},600)});show();
